# Generated by Django 5.0.1 on 2024-01-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
